[package]
name = "mowz"
version = "0.1.1"
edition = "2024"
description = "mowz retrieves production context"
repository = "https://github.com/siosw/mowz"
homepage = "https://github.com/siosw/mowz"
readme = "README.md"
license = "GPL-3.0-or-later"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["clock"] }
clap = { version = "4", features = ["derive"] }
eyre = "0.6"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
toml = "0.9"

[dev-dependencies]
tempfile = "3"
wiremock = "0.6"
